dartoos-dev/json_cache

README.md
In a nutshell:
- enhances the introductory text;
- add content to the Getting Started section.
Closes #10
=> doc(README): improve the package description and examples

.github/workflows/build.yml, .rultor.yml, CHANGELOG.md, README.md, analysis_options.yaml, pubspec.lock, pubspec.yaml
=> build: structural configurations

CHANGELOG.md, README.md, lib/json_cache.dart, lib/src/json_cache.dart, lib/src/json_cache_fake.dart, lib/src/json_cache_mem.dart, lib/src/json_cache_prefs.dart, lib/src/json_cache_wrap.dart, pubspec.lock, pubspec.yaml, test/json_cache_mem_test.dart, test/json_cache_prefs_test.dart, test/json_cache_wrap_test.dart
=> feat: JsonCachePrefs class

CHANGELOG.md, README.md, lib/json_cache.dart, lib/src/json_cache_local_storage.dart, lib/src/json_cache_mem.dart, pubspec.lock, pubspec.yaml, test/json_cache_local_storage_test.dart
=> feat: JsonCacheLocalStorage

CHANGELOG.md, lib/src/json_cache_cross_local_storage.dart, lib/src/json_cache_enc_prefs.dart, lib/src/json_cache_hollow.dart, lib/src/json_cache_local_storage.dart, lib/src/json_cache_mem.dart, lib/src/json_cache_prefs.dart, lib/src/json_cache_wrap.dart, pubspec.lock, pubspec.yaml
=> style: stricter linting rules

CHANGELOG.md, README.md, lib/json_cache.dart, lib/src/json_cache.dart, lib/src/json_cache_fake.dart, lib/src/json_cache_sec_storage.dart, pubspec.lock, pubspec.yaml, test/flutter_secure_storage_mock.dart, test/json_cache_sec_storage_test.dart
=> feat: create JsonCacheSecStorage

CHANGELOG.md, README.md
=> chore: fix project logo image

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> build: bump up dependencies

CHANGELOG.md, pubspec.yaml
=> fix: the value of the version field of the pubscpec file

CHANGELOG.md, lib/src/json_cache_fake.dart, lib/src/json_cache_hollow.dart, lib/src/json_cache_mem.dart, lib/src/json_cache_wrap.dart
=> chore: add code style improvements

README.md
=> doc(README): minor corrections

CHANGELOG.md, README.md, lib/json_cache.dart, lib/src/json_cache.dart, lib/src/json_cache_cross_local_storage.dart, lib/src/json_cache_enc_prefs.dart, lib/src/json_cache_fake.dart, lib/src/json_cache_hive.dart, lib/src/json_cache_hollow.dart, lib/src/json_cache_local_storage.dart, lib/src/json_cache_mem.dart, lib/src/json_cache_prefs.dart, lib/src/json_cache_sec_storage.dart, lib/src/json_cache_wrap.dart, test/json_cache_cross_local_storage_test.dart, test/json_cache_enc_prefs_test.dart, test/json_cache_fake_test.dart, test/json_cache_hive_test.dart, test/json_cache_local_storage_test.dart, test/json_cache_mem_test.dart, test/json_cache_prefs_test.dart, test/json_cache_sec_storage_test.dart, test/json_cache_wrap_test.dart
=> feat: implementation of the 'contains' method

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> build: update 'flutter_secure_storage' to version 6.0.0

CHANGELOG.md, test/json_cache_try_test.dart
=> fix: linter error

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> set flutter_secure_storage to version 8.0.0

CHANGELOG.md, lib/json_cache.dart, lib/src/json_cache_safe_local_storage.dart, pubspec.lock, pubspec.yaml, test/json_cache_safe_local_storage_test.dart
feat: JsonCacheSafeLocalStorage class
=> feat: JsonCacheSafeLocalStorage class

CHANGELOG.md, README.md
=> doc: JsonCacheSafeLocalStorage info in README

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> bump up dependencies

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> build: remove unused package 'cross_local_storage'

CHANGELOG.md, analysis_options.yaml, pubspec.lock, pubspec.yaml, test/json_cache_fake_test.dart, test/json_cache_flutter_secure_storage_test.dart, test/json_cache_hive_test.dart, test/json_cache_local_storage_test.dart, test/json_cache_mem_test.dart, test/json_cache_safe_local_storage_test.dart, test/json_cache_shared_preferences_test.dart, test/json_cache_wrap_test.dart
refactor: updated sdk constraints and removed warnings
=> refactor: updated sdk constraints and removed warnings 

.github/workflows/build.yml, .rultor.yml
=> ci(rultor): update Flutter docker image

.github/workflows/build.yml
=> ci(github actions): add 'master' to the 'pull_request' section

CHANGELOG.md, pubspec.yaml
=> release: 3.0.2

CHANGELOG.md, pubspec.yaml
=> release: 4.0.0

CHANGELOG.md, README.md
=> fix: minor error in README file
